server.port=8082
spring.application.name=doctor-service
spring.data.mongodb.uri=mongodb+srv://imethweerasooriya_db_user:0ZPnRdbn6sgbiNNd@cluster0.dndzifx.mongodb.net/edoc_doctor_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=edoc_doctor_db
jwt.secret=eDocSecretKey2026SuperSecureKeyForJWTTokenGeneration
jwt.expiration=86400000
logging.level.com.edoc=DEBUG
spring.mongodb.embedded.version=