server:
  port: 8082

spring:
  application:
    name: doctor-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: edoc_doctor_db

jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH:backend/user-service/secrets/public.pem}
  expiration: 86400000

patient:
  service:
    url: http://localhost:8084

logging:
  level:
    com.edoc: DEBUG