server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: doctor-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: edoc_doctor_db

jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH:secrets/public.pem}

patient:
  service:
    url: ${PATIENT_SERVICE_URL:http://patient-service:8084}

logging:
  level:
    com.edoc: DEBUG