server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: appointment-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: edoc_appointment_db

jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH:secrets/public.pem}
  expiration: ${JWT_EXPIRATION:86400000}

doctor:
  service:
    url: ${DOCTOR_SERVICE_URL:http://doctor-service:8082}

patient:
  service:
    url: ${PATIENT_SERVICE_URL:http://patient-service:8084}

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8083}

logging:
  level:
    com.edoc: DEBUG