server.port=8081
spring.application.name=appointment-service
spring.data.mongodb.uri=mongodb+srv://imethweerasooriya_db_user:0ZPnRdbn6sgbiNNd@cluster0.dndzifx.mongodb.net/edoc_appointment_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=edoc_appointment_db
jwt.secret=eDocSecretKey2026SuperSecureKeyForJWTTokenGeneration
jwt.expiration=86400000
doctor.service.url=http://localhost:8082
logging.level.com.edoc=DEBUG