server.port=8081
spring.application.name=appointment-service
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=edoc_appointment_db
jwt.secret=eDocSecretKey2026SuperSecureKeyForJWTTokenGeneration
jwt.expiration=86400000
doctor.service.url=http://localhost:8082
patient.service.url=http://localhost:8084
notification.service.url=http://localhost:8083
logging.level.com.edoc=DEBUG