# Server port - appointment service runs on 8083
server.port=8081

# Application name
spring.application.name=appointment-service

# MongoDB connection - separate database from doctor-service
spring.data.mongodb.uri=mongodb://localhost:27017/edoc_appointment_db
spring.data.mongodb.database=edoc_appointment_db

# JWT Secret - MUST be exactly the same string as doctor-service
jwt.secret=eDocSecretKey2026SuperSecureKeyForJWTTokenGeneration
jwt.expiration=86400000

# Doctor service URL - appointment service calls this to get doctor info
doctor.service.url=http://localhost:8082

# Logging
logging.level.com.edoc=DEBUG