spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:notification_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8083}

doctor-service:
  base-url: ${DOCTOR_SERVICE_URL:http://localhost:8082}

resend:
  api-key: ${RESEND_API_KEY:}
  from-email: ${RESEND_FROM_EMAIL:onboarding@resend.dev}
  api-url: ${RESEND_API_URL:https://api.resend.com/emails}
  test-recipient: ${RESEND_TEST_RECIPIENT:lehanxp@gmail.com}

vonage:
  api-key: ${VONAGE_API_KEY:}
  api-secret: ${VONAGE_API_SECRET:}
  sms-from: ${VONAGE_SMS_FROM:eDoc}

jwt:
  public-key: ${JWT_PUBLIC_KEY:}
