spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:patient_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${JWT_PUBLIC_KEY_LOCATION:classpath:public.pem}

server:
  port: ${SERVER_PORT:8084}

app:
  storage:
    reports-dir: ${REPORTS_DIR:uploads/reports}

doctor-service:
  base-url: ${DOCTOR_SERVICE_URL:http://doctor-service:8082}

jwt:
  public-key-base64: ${JWT_PUBLIC_KEY_BASE64:}
