apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
  namespace: edoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-db
  template:
    metadata:
      labels:
        app: user-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: user_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: edoc-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: edoc-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U user -d user_db
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-db
  namespace: edoc
spec:
  selector:
    app: user-service-db
  ports:
    - port: 5432
      targetPort: 5432

