apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-service-db-init-sql
  namespace: edoc
data:
  init.sql: |
    CREATE SCHEMA IF NOT EXISTS app;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patient-service-db-init
  namespace: edoc
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: postgres:16-alpine
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: edoc-secrets
                  key: DB_PASSWORD
          command: ["/bin/sh", "-c"]
          args:
            - psql -h patient-service-db -U user -d patient_db -f /init/init.sql
          volumeMounts:
            - name: init-sql
              mountPath: /init
      volumes:
        - name: init-sql
          configMap:
            name: patient-service-db-init-sql

